# Generated by Django 5.2.17 on 2026-08-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=64)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
